#!/usr/bin/env ansible-playbook
---

- include: /usr/local/share/ansible/check-ansible-version.yml
- include: /usr/local/share/ansible/check-git-version.yml

- hosts: localhost
  tags: global
  name: Set git basic global config default
  tasks:
    - git_config:
        scope: global
        name: '{{ item.key }}'
        value: '{{ item.value }}'
      with_dict:
        push.default: simple
        user.mail: t.delamare@laposte.net
        user.name: Thierry Delamare

- hosts: localhost
  tags: aliases
  name: Set git basic global aliases default
  tasks:
    - git_config:
        scope: global
        name: alias.{{ item.key }}
        value: '{{ item.value }}'
      with_dict:
        br: branch
        ci: commit
        co: checkout
        fe: fetch
        st: status
        lo: log -n10

- hosts: localhost
  tags: show
  name: Show configured git user email
  tasks:
    - git_config:
        scope: local
        repo: &repo '{{ repo | default(".") }}'
        name: '{{ name | default("user.email") }}'
      register: git_config
    - debug: { var: git_config.config_value }

- hosts: localhost
  tags: email
  name: Set local git user email from remote origin
  tasks:
    - command: git remote get-url origin
      args: { chdir: *repo }
      check_mode: False
      changed_when: False
      register: url
    - set_fact: { pseudo: '{{ url.stdout.split(":")[0] }}' }
    - set_fact:
        pseudos:
          default: &default t.delamare@laposte.net
          wato.ssh: *default
          git@thydel.github.com: *default
          git@thyepi.github.com: t.delamare@epiconcept.fr
    - git_config:
        scope: local
        repo: *repo
        name: user.email
        value: '{{ pseudos[pseudo] | default(pseudos.default) }}'

- hosts: localhost
  tags: log
  name: Set local git config
  tasks:
    - git_config:
        scope: local
        repo: *repo
        name: '{{ item.key }}'
        value: '{{ item.value }}'
      with_dict:
        push.default: simple
        tag.sort: 'version:refname'
        log.date: relative
        format.pretty: >-
          tformat:%C(auto,yellow)%h%C(auto,magenta)% G?
          %C(auto,blue)%>(12,trunc)%ad
          %C(auto,green)%<(8,trunc)%aN%C(auto,reset)%s%C(auto,red)% %d
          %C(auto,reset)

- hosts: localhost
  tags: mailmap
  name: Set git mailmap
  tasks:
    - lineinfile:
        path: '{{ repo | default(playbook_dir) }}/.mailmap'
        line: '{{ item }}'
        create: True
      with_items:
        - thyepi <t.delamare@epiconcept.fr> Thierry Delamare
        - thydel <t.delamare@laposte.net>   Thierry Delamare
        - evens  <e.solignac@epiconcept.fr> Evens Solignac
        - cedric <c.girard@epiconcept.fr>   Cédric Girard
    - lineinfile:
        path: '{{ repo | default(playbook_dir) }}/.git/info/exclude'
        line: '{{ item }}'
        insertafter: '^\*~$'
      with_items: [ .mailmap, .stone ]
